### ISSUE TITLE
Brand new install not working

### ISSUE THREAD

**Issue by adigitalnative** [zurb/foundation-rails#260]
I've installed Foundation on a brand new rails install, and while I hit no error messages, none of my content is being formatted as I would expect.

I'm at ruby 2.2.1 and rails 4.2.5.1. (Yes, I need to upgrade. Still, it /should/ work...)

Performed the standard install:
Gemfile:
`
gem 'foundation-rails'
gem 'autoprefixer-rails'
`
Then ran
`bundle install`
and
`rails g foundation:install`

Accepted the overwrite of application.html.erb

When I load a webpage, I get unformatted text. Using `<div class="row"><div class="small-12 columns">` etc doesn't change formatting. I've emptied my browser cache etc so the issue isn't there.

A) I'm missing an install step.
B) The Readme is missing that install step too.

Thoughts? Completely willing to believe that this is a rails version issue, but if so some info in the readme about what versions of Rails are compatible would be quite helpful...

**Comment by ncoden** [comment]
Hi @adigitalnative,

From Foundation 6.4.0, the XY grid is the default grid and the Float or Flex grids are no longer included. So you should use:
```html
<div class="grid-x grid-padding-x">
    <div class="cell small-12">...</div>
</div>
```

I would recommend you to take a look at the [XY Grid documentation](https://foundation.zurb.com/sites/docs/xy-grid.html) to see how to use it (or to go back to the legacy Float Grid).

**Comment by adigitalnative** [comment]
I don't think that's the issue, since it's not just a grid thing - styles don't seem to be applied.

`<%= link_to "Add Foo", new_foo_path, class: "button" %>` 

gives me an unstyled link, not a button. H2 tags appear to be using the user agent stylesheet, not anything from the Foundation CSS.

Again, this may either be version or Silly Developer Error - but since it's an uncomplicated app install, seemed like it /should/ work out of the box...

**Comment by ncoden** [comment]
Did you correctly followed the installations instructions for Sass ?
See https://github.com/zurb/foundation-rails#manual-installation

**Comment by rehmanh** [comment]
I am having the same issue that @adigitalnative described above. 

After installing Foundation-Rails from the guide in the ReadMe, I was able to make some classes work. For some strange reason, not all classes are working. This led me to believe that I installed Foundation incorrectly, but I also tried performing the steps in the Manual Installation and am still experiencing this issue. 

Buttons and forms will render just fine, but when I copied [this](https://codepen.io/IamManchanda/pen/eWrwKP?editors=1000) code to render a navbar, my app doesn't seem to render it correctly. The styles appear vertically positioned, without any real styling, and when I inspect the elements, the classes specified seem to be empty. 

I just think this is extremely strange – Foundation _IS_ working, just not all the resources that would otherwise be available. 

You can check out the code in my repo: github.com/rehmanh/Aesthetic-Clinic/ and confirm that I am doing everything correctly. 

Thanks!

**Comment by ncoden** [comment]
@rehmanh The navbar code you copied is for Foundation v6.3.1. Some stuff changed from the previous versions like menus which have been simplified. Could you tell which version of Foundation you are using and check in the [Documentation](https://foundation.zurb.com/sites/docs/) that your code is up-to-date ?

**Comment by rehmanh** [comment]
@ncoden thank you so much! I assumed that by not specified the gem version, it would automatically install the most recent gem, but was not aware of dependencies from other gems. 

This seems to work just fine now, with the most recent gem. Once again, thank you so much!

**Comment by ncoden** [comment]
I'm closing this issue as I did not get reply from @adigitalnative
