### ISSUE TITLE
!default flag in settings by default

### ISSUE THREAD

**Issue by kirylpl** [zurb/foundation-rails#261]
Why there is no use !default flag for easier settings customizing?
After upgrade we have should manually check settings file to update my custom variables, and that's no funny when realizing that it can be just copy-pase of pre-defined vars before..
That's not normal.
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default

**Comment by ncoden** [comment]
Hi @kirylpl.

Default settings are already defined inside each component (with a `default` flag). The `_settings` file is not used by Foundation is intended to be copied into your own project to customize Foundation. You can modify this file as you want and remove all settings. I would recommand you to comment everything and leave uncommented only the settings you changed.

I hope this anwsers your question. Please reopen otherwise.
